version: "3.9"  # optional since v1.27.0
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
  academia:
    depends_on:
      - mysqldb
    env_file:
      - ./.env
    build: .
    environment:
      - NODE_ENV=$NODE_ENV
      - API_KEY=$API_KEY
      - JWT_SECRET_KEY=$JWT_SECRET_KEY
      - JWT_ACCESS_TOKEN_INVALIDATION_TIME=$JWT_ACCESS_TOKEN_INVALIDATION_TIME
      - JWT_REFRESH_TOKEN_INVALIDATION_TIME=$JWT_REFRESH_TOKEN_INVALIDATION_TIME
      - FB_CLIENT_ID=$FB_CLIENT_ID
      - FB_CLIENT_SECRET=$FB_CLIENT_SECRET
      - GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
      - S3_ACCESS_KEY=$S3_ACCESS_KEY
      - S3_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY
      - S3_BUCKET=$S3_BUCKET
      - S3_REGION=$S3_REGION
      - IYZIPAY_API_KEY=$IYZIPAY_API_KEY
      - IYZIPAY_SECRET_KEY=$IYZIPAY_SECRET_KEY
      - IYZIPAY_URI=$IYZIPAY_URI
      - MYSQLDB_USER=$MYSQLDB_USER
      - MYSQLDB_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQLDB_DATABASE=$MYSQLDB_DATABASE
      - MYSQLDB_LOCAL_PORT=$MYSQLDB_LOCAL_PORT
      - MYSQLDB_DOCKER_PORT=$MYSQLDB_DOCKER_PORT
    ports:
      - "9000:3050"
    networks:
      - backend
    command: bash -c 'while !</dev/tcp/mysqldb/3306; do sleep 1; done; npm start'
    stdin_open: true
    tty: true
networks:
  backend:
volumes:
  db:
